import { StyleSheet } from 'react-native';

export const styledCard = StyleSheet.create({
  container: {
    display: 'flex',
    flexDirection: 'column',
    width: '48%',
    marginBottom: 12,
    backgroundColor: 'transparent'
  },
  listOptions: {
    backgroundColor: 'rgba(248, 214, 209, 0.85)',
    marginBottom: 10,
    borderRadius: 12,
    overflow: 'hidden',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  accordionContent: {
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  unitsCount: {
    fontSize: 13,
    fontWeight: '600',
    color: '#8B4C42',
    marginBottom: 12,
    textAlign: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
    alignSelf: 'center',
  },
  noUnitsText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#999',
    marginBottom: 12,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  cardContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
  },
  containerTitle: {
    backgroundColor: 'rgba(205, 76, 62, 0.6)',
    borderRadius: 10,
    padding: 5,
    textAlign: 'center',
  },
  title: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#fff',
  },
  description: {
    fontSize: 12,
    color: '#fff',
    fontWeight: '600',
  },
  listContainer: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    gap: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  createCardWrapper: {
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: 'rgba(222, 139, 129, 0.6)',
  },
  createCardContent: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 14,
    gap: 10,
    minHeight: 120,
    backgroundColor: 'rgba(222, 139, 129, 0.6)',
    borderWidth: 2,
    borderColor: 'rgba(205, 76, 62, 0.4)',
    borderStyle: 'dashed',
    borderRadius: 14,
  },
  createCardIconWrapper: {
    backgroundColor: '#CD4C3E',
    margin: 0,
  },
  createCardTextWrapper: {
    backgroundColor: 'rgba(90, 17, 17, 0.4)',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  createCardText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#fff',
  },
});
